# -*- coding: utf-8 -*-
"""ALiCaS-B Model Updated

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12UYmmY0DNvOyKbccFAzYbtj3i4DKBIEX

Connect google drive to collab project
"""

from google.colab import drive
drive.mount('/content/drive')

"""change derectory to actual data set"""

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/My Drive/Shanuka Dataset"

"""Unzip the data"""

!unzip "Copy of badmintonc.zip"

"""Add data.yml

"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile badmintonc/data.yaml
# train: ./BadmintonC.v1-version-01-badmintonc.yolov8/train/images
# val: ./BadmintonC.v1-version-01-badmintonc.yolov8/valid/images
# test: ./BadmintonC.v1-version-01-badmintonc.yolov8/test/images
# 
# nc: 2
# names: ['-', 'court']

"""Install YOLOv8"""

!pip install ultralytics

from ultralytics import YOLO

model = YOLO('yolov8n.pt')

results = model.train(
    data='badmintonc/data.yaml',
    epochs=50,
    imgsz=640,
    batch=8
)