# -*- coding: utf-8 -*-
"""Shuttlecock.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nkE2MEl4tVS59HH6-_C3AtBg5h1i89lm

Import libraries
"""

!pip install ultralytics

from ultralytics import YOLO

import ultralytics
print(ultralytics.__version__)

"""mount drive"""

from google.colab import drive
drive.mount('/content/drive')

"""unzip the data set"""

# Commented out IPython magic to ensure Python compatibility.
# %cd "/content/drive/My Drive/Shanuka_Dataset/Shuttlecock"

!unzip "Copy of shuttlecock.zip"

YAML_PATH = '/content/drive/My Drive/Shanuka_Dataset/Shuttlecock/shuttlecock/Shuttlecock.v1-version-01-shuttlecock.yolov8/data.yaml'

model = YOLO('yolov8n.pt')

results = model.train(
    data=YAML_PATH,
    epochs=50,
    imgsz=640,
    batch=-1,
    name='Shuttlecock_Run1',
    patience=50,
    cache=True
)